---
before_install:
  - wget -O /tmp/chefdk.deb https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.3.5-1_amd64.deb
install:
  - sudo dpkg -i /tmp/chefdk.deb
before_script:
  - berks install
  - chef gem install strainer --no-rdoc --no-ri
  # TODO: chef gem install -f
script:
  - chef exec strainer test
notifications:
  hipchat:
    secure: ! 'Qq7cHtvRKNMWa/Kj2NCmEVRkgJUFygVSBoDe8Irth/P6wHUHzKN/aGc1TxW8

      Ykpr+qjv0b2JYHlsydcibIKOP86hHXWaJbXO5zpJJrsbfgj+cljRu9jeZ/Wc

      xGxKKVqugxSAvp0GeZsf43jSZ4jmehX1UESoEBHJjGxFxryzXVI='
